src/Entity/Profile.php
<?php

namespace App\Entity;

use App\Repository\ProfileRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProfileRepository::class)
 */
class Profile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $last_name;

    /**
     * @ORM\ManyToOne(targetEntity=UserCat::class)
     */
    private ?UserCat $user_cat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $address;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $zipcode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $phone;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $available;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $last_update;

    /**
     * @ORM\ManyToMany(targetEntity=Skill::class, inversedBy="profiles")
     */
    private Collection $skills;

    /**
     * @ORM\OneToMany(targetEntity=History::class, mappedBy="profile")
     */
    private Collection $history;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="profile", cascade={"persist", "remove"})
     */
    private ?User $user;

    public function __construct()
    {
        $this->skills = new ArrayCollection();
        $this->history = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getUserCat(): ?UserCat
    {
        return $this->user_cat;
    }

    public function setUserCat(?UserCat $user_cat): self
    {
        $this->user_cat = $user_cat;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAvailable(): ?bool
    {
        return $this->available;
    }

    public function setAvailable(bool $available): self
    {
        $this->available = $available;

        return $this;
    }

    public function getLastUpdate(): ?\DateTimeInterface
    {
        return $this->last_update;
    }

    /**
     * @ORM\PrePersist
     */
    public function setLastUpdate(\DateTimeInterface $last_update): self
    {
        $this->last_update = new \DateTime();

        return $this;
    }

    /**
     * @return Collection|Skill[]
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills[] = $skill;
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        $this->skills->removeElement($skill);

        return $this;
    }

    /**
     * @return Collection|History[]
     */
    public function getHistory(): Collection
    {
        return $this->history;
    }

    public function addHistory(History $history): self
    {
        if (!$this->history->contains($history)) {
            $this->history[] = $history;
            $history->setProfile($this);
        }

        return $this;
    }

    public function removeHistory(History $history): self
    {
        if ($this->history->removeElement($history)) {
            // set the owning side to null (unless already changed)
            if ($history->getProfile() === $this) {
                $history->setProfile(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setProfile(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getProfile() !== $this) {
            $user->setProfile($this);
        }

        $this->user = $user;

        return $this;
    }

    public function __toString()
    {
        return "{$this->getFirstName()} {$this->getLastName()}";
    }
}

src/Entity/Skill.php
<?php

namespace App\Entity;

use App\Repository\SkillRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SkillRepository::class)
 */
class Skill
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $name;

    public function __toString() {
        return $this->name;
    }

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $liked;

    /**
     * @ORM\ManyToOne(targetEntity=SkillCat::class)
     */
    private ?SkillCat $skill_cat;

    /**
     * @ORM\ManyToOne(targetEntity=Level::class)
     */
    private ?Level $level;

    /**
     * @ORM\ManyToMany(targetEntity=Profile::class, mappedBy="skills")
     */
    private Collection $profiles;

    public function __construct()
    {
        $this->profiles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLiked(): ?bool
    {
        return $this->liked;
    }

    public function setLiked(bool $liked): self
    {
        $this->liked = $liked;

        return $this;
    }

    public function getSkillCat(): ?SkillCat
    {
        return $this->skill_cat;
    }

    public function setSkillCat(?SkillCat $skill_cat): self
    {
        $this->skill_cat = $skill_cat;

        return $this;
    }

    public function getLevel(): ?Level
    {
        return $this->level;
    }

    public function setLevel(?Level $level): self
    {
        $this->level = $level;

        return $this;
    }

    /**
     * @return Collection|Profile[]
     */
    public function getProfiles(): Collection
    {
        return $this->profiles;
    }

    public function addProfile(Profile $profile): self
    {
        if (!$this->profiles->contains($profile)) {
            $this->profiles[] = $profile;
            $profile->addSkill($this);
        }

        return $this;
    }

    public function removeProfile(Profile $profile): self
    {
        if ($this->profiles->removeElement($profile)) {
            $profile->removeSkill($this);
        }

        return $this;
    }
}

src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\Profile;
use App\Entity\UserCat;
use App\Entity\Skill;
use App\Entity\History;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name', TextType::class, [
                'label' => 'Your first name',
                'attr' => [
                    'placeholder' => 'Leila'
                ]
            ])
            ->add('last_name', TextType::class, [
                'label' => 'Your last name',
                'attr' => [
                    'placeholder' => 'Smith'
                ]
            ])
            ->add('address', TextType::class, [
                'label' => 'Your address',
                'attr' => [
                    'placeholder' => '21 Mean Street'
                ]
            ])
            ->add('zipcode', IntegerType::class, [
                'label' => 'Zip Code',
                'attr' => [
                    'placeholder' => '00000'
                ]
            ])
            ->add('city', TextType::class, [
                'label' => 'Your city',
                'attr' => [
                    'placeholder' => 'London'
                ]
            ])
            ->add('email', TextType::class, [
                'label' => 'Your email',
                'attr' => [
                    'placeholder' => 'my.real.email@yeahsure.com'
                ]
            ])
            ->add('phone', TextType::class, [
                'label' => 'Your phone number',
                'attr' => [
                    'placeholder' => '0000000000'
                ]
            ])
            ->add('available', CheckboxType::class, [
                'label' => 'Available'
            ])
            ->add('user_cat', EntityType::class, [
                'label' => 'You are currently a ... :',
                'class' => UserCat::class,
                'choice_label' => 'name',
                'expanded' => true
//                'multiple'     => true
            ])
            ->add('skills', EntityType::class, [
                'class' => Skill::class,
                'choice_label' => function($skill) {
                    return $skill->getName() . ' - ' . $skill->getSkillCat();
                },
                'expanded' => true,
                'multiple' => true,
                'group_by' => function($skill){
                    return $skill->getSkillCat();
                }
            ])
//            ->add('history', History::class, [
//                'label' => 'Your history'
//            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Profile::class,
        ]);
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Profile;
use App\Form\ProfileType;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    
    /**
     * @Route("{id}/profile", name="profile")
     */
    public function index(User $user): Response
    {   
        $profiles = $this->entityManager->getRepository(Profile::class)->findAll();
        $profile = $this->entityManager->getRepository(Profile::class)->find($this->getUser());
        return $this->render('profile/index.html.twig', [
            'controller_name' => 'ProfileController',
            'profile' => $profile,
        ]);
    }

    /**
     * @Route("{id}/profile/new", name="new_profile")
     */
    public function new(Request $request, User $user)
    {
        $profile = new Profile();
        $form = $this->createForm(ProfileType::class, $profile);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $profile = $form->getData();

            $this->entityManager->persist($profile);
            $this->entityManager->flush();
            $user->setProfile($profile);
            $this->entityManager->flush();

            return $this->redirectToRoute('profile');
        }

        return $this->render(
            'profile/new.html.twig',
            ['form_profile' => $form->createView()]
        );
    }
}

templates/profile/index.html.twig
{% extends 'home/index.html.twig' %}

{% block content %}
    <div class="container w-75 border border-danger rounded shadow bg-white mt-3">
        <div class="border border-danger rounded mt-3 p-2">
            <h3>{{ profile.firstName }} {{ profile.lastName }}</h3>
            <p>{{ profile.userCat }}</p>
        </div>
        <div class="border border-danger rounded mt-3 p-2">
            <h4>My address</h4>
            <p>{{ profile.address }}</p>
            <p>{{ profile.zipcode }} {{ profile.city }}</p>
        </div>
        <div class="border border-danger rounded mt-3 p-2">
            <h4>Contact</h4>
            <p>{{ profile.email }} - {{ profile.phone }}</p>

        </div>
        {% if (profile.available) %}
            <p class="text-success mt-3">Currently available</p>
        {% else %}
            <p class="text-warning mt-3">Not available at the moment</p>
        {% endif %}
        <div class="border border-danger rounded my-3 p-2">
            {% for skill in profile.skills %}
                <h4>Skills</h4>
                <div>
                    <p>{{ skill.name }}- {{ skill.skillCat }}</p>
                    {% if (skill.liked) %}
                        <i class="bi bi-heart"></i>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/profile/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form_profile 'bootstrap_4_layout.html.twig' %}
{% block title %}New profile{% endblock %}
{% block content %}
    <div class="container text-center w-75">
        <h2 class="p-4 m-4 bg-white border border-info rounded shadow">Please, complete your profile</h2>
        <button class="btn btn-info col-4 mb-3 shadow" href="{{ path('home') }}">I'll do it later</button>
        <div class="rounded border border-warning bg-white round p-4 text-start shadow">
            {{ form_start(form_profile) }}
            <div class="row">
                <div class="form-group col p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.first_name, {"attr": {"class" : "form-control"}}) }}
                </div>
                <div class="form-group col p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.last_name, {"attr": {"class" : "form-control"}}) }}
                </div>
            </div>
            <div class="form-group p-2 rounded bg-light mb-3">
                {{ form_row(form_profile.address, {"attr": {"class" : "form-control"}}) }}
            </div>
            <div class="row">
                <div class="form-group col p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.zipcode, {"attr": {"class" : "form-control"}}) }}
                </div>
                <div class="form-group col p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.city, {"attr": {"class" : "form-control"}}) }}
                </div>
            </div>
                <div class="form-group p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.email, {"attr": {"class" : "form-control"}}) }}
                </div>
                <div class="form-group p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.phone, {"attr": {"class" : "form-control"}}) }}
                </div>
                <div class="form-group p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.available) }}
                </div>
                <div class="form-group p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.user_cat) }}
                </div>
                <div class="form-group p-2 rounded bg-light mb-3">
                    {{ form_row(form_profile.skills) }}
                </div>
                <button class="submit btn btn-success col-4 float-end mb-3">Save</button>
            {{ form_end(form_profile) }}
        </div>
    </div>
{% endblock %}