src/Entity/History.php
<?php

namespace App\Entity;

use App\Repository\HistoryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HistoryRepository::class)
 */
class History
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $position;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $place;

    /**
     * @ORM\ManyToOne(targetEntity=Company::class)
     */
    private ?Company $company;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $start_date;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $end_date;

    /**
     * @ORM\Column(type="text")
     */
    private ?string $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $context;

    /**
     * @ORM\Column(type="text")
     */
    private ?string $technical_env;

    /**
     * @ORM\ManyToOne(targetEntity=Profile::class, inversedBy="history")
     */
    private ?Profile $profile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(string $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContext(): ?string
    {
        return $this->context;
    }

    public function setContext(string $context): self
    {
        $this->context = $context;

        return $this;
    }

    public function getTechnicalEnv(): ?string
    {
        return $this->technical_env;
    }

    public function setTechnicalEnv(string $technical_env): self
    {
        $this->technical_env = $technical_env;

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(?Profile $profile): self
    {
        $this->profile = $profile;

        return $this;
    }
}

src/Form/HistoryType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\History;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HistoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('position', TextType::class, [
                'label' => 'Position',
                'attr' => [
                    'placeholder' => 'e.g. Project Manager'
                ]
            ])
            ->add('place', TextType::class, [
                'label' => 'Where ?',
                'attr' => [
                    'placeholder' => 'e.g. London'
                ]
            ])
            ->add('start_date', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('end_date', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Describe this experience',
                'attr' => [
                    'placeholder' => '...'
                ]
            ])
            ->add('context', TextareaType::class, [
                'label' => 'Context',
                'attr' => [
                    'placeholder' => '...'
                ]
            ])
            ->add('technical_env', TextType::class, [
                'label' => 'Technical environment',
                'attr' => [
                    'placeholder' => 'e.g. Node.js, React, Kubernetes, etc.'
                ]
            ])
            ->add('company', EntityType::class, [
                'class' => Company::class,
                'choice_label' => 'name',
                'expanded' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => History::class,
        ]);
    }
}

src/Controller/HistoryController.php
<?php

namespace App\Controller;

use App\Entity\History;
use App\Entity\User;
use App\Entity\Profile;
use App\Form\HistoryType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HistoryController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("{id}/history", name="history")
     */
    public function index(User $user): Response
    {
        $history = $this->entityManager->getRepository(History::class)->find($this->getUser());
        return $this->render('history/index.html.twig', [
            'controller_name' => 'HistoryController',
            'history' => $history
        ]);
    }

    /**
     * @Route("{id}/history/new", name="new_history")
     */
    public function new(Request $request, Profile $profile )
    {
        $history = new History();
        $form = $this->createForm(HistoryType::class, $history);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $history = $form->getData();

            $this->entityManager->persist($history);
            $this->entityManager->flush();
            $profile->addHistory($history);
            $this->entityManager->flush();

            return $this->redirectToRoute('history');
        }

        return $this->render(
            'history/new.html.twig',
            ['form_history' => $form->createView()]
        );
    }
}

templates/history/index.html.twig
{% extends 'home/index.html.twig' %}

{% block content %}
<div class="container w-75 border border-success rounded shadow bg-white mt-3">
    <div class="border border-success rounded mt-3 p-2">
        <h3>{{ history.position }} @ {{ history.company }}</h3>
        <p>in {{ history.place }}</p>
    </div>
    <div class="border border-success rounded mt-3 p-2">
        <h4>Details</h4>
        <p>{{ history.startDate|date }} {{ history.endDate|date }}</p>
        <p>{{ history.description }}</p>
        <p>{{ history.context }}</p>
    </div>
    <div class="border border-success rounded mt-3 p-2 mb-3">
        <h4>Techs I used</h4>
        <p>{{ history.technicalEnv }}</p>
    </div>
</div>
{% endblock %}

templates/history/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form_history 'bootstrap_4_layout.html.twig' %}
{% block title %}New history{% endblock %}
{% block content %}
    <div class="container text-center w-75">
        <h2 class="p-4 m-4 bg-white border border-info rounded shadow">Please, complete your profile</h2>
        <button class="btn btn-info col-4 mb-3 shadow" href="{{ path('home') }}">I'll do it later</button>
        <div class="rounded border border-success bg-white round p-4 text-start shadow">
            {{ form_start(form_history) }}
            <div class="row">
                <div class="form-group col p-2 rounded bg-light mb-3">
                    {{ form_row(form_history.position, {"attr": {"class" : "form-control"}}) }}
                </div>
                <div class="form-group col p-2 rounded bg-light mb-3">
                    {{ form_row(form_history.place, {"attr": {"class" : "form-control"}}) }}
                </div>
                <div class="form-group p-2 rounded bg-light mb-3">
                    {{ form_row(form_history.company) }}
                </div>
            </div>
            <div class="row">
                <div class="form-group col p-2 rounded bg-light mb-3">
                    <label>From...</label>
                    {{ form_widget(form_history.start_date) }}
                </div>
                <div class="form-group col p-2 rounded bg-light mb-3">
                    <label>...to...</label>
                    {{ form_widget(form_history.end_date) }}
                </div>
            </div>
            <div class="form-group p-2 rounded bg-light mb-3">
                {{ form_row(form_history.description, {"attr": {"class" : "form-control"}}) }}
            </div>
            <div class="form-group p-2 rounded bg-light mb-3">
                {{ form_row(form_history.technical_env, {"attr": {"class" : "form-control"}}) }}
            </div>
            <div class="form-group p-2 rounded bg-light mb-3">
                {{ form_row(form_history.context, {"attr": {"class" : "form-control"}}) }}
            </div>
            <button class="submit btn btn-success col-4 float-end mb-3">Save</button>
            {{ form_end(form_history) }}
        </div>
    </div>
{% endblock %}